vivliostyle/vfm

spec/vfm.md
`なろう` -> `視覚障碍者読書支援協会 (BBA)「原文入力ルール」`
=> docs: fix ref for the ruby notation

package.json
2021/1/9 の開発者会議で `npm publish` 時に `next` タグは付けず、そのまま alpha としてリリースすることになったのでコマンドから当該箇所を削除。
=> #42 Removed npm's "next" tag in pre-release

src/cli.ts
CLI オプションの `--partial` におけるショートハンドは `-p` だが `--help` 表示は `-s` になっているため、修正。
=> fix: CLI option shorthand mistake #56

tests/utils.ts
#50 のためにテスト時の VFM オプション変更が必要となったため buildProcessorTestingCode へ引数を追加。
=> chore: Add VFM options to buildProcessorTestingCode #59

README.md, src/cli.ts, src/index.ts, src/revive-parse.ts, tests/block/line-breaks.test.ts, tests/index.test.ts, tests/inline/ruby.test.ts, tests/utils.ts
=> feat: Change automatic line breaks to optional

README.md, package.json, src/cli.ts, src/index.ts, tests/index.test.ts, tests/remark2rehype/html-formatter.test.ts, tests/remark2rehype/html-lang.test.ts, tests/utils.ts, types/remark.d.ts, yarn.lock
HTML を人間がよみやすく整形する機能を実装しました。Prettier ではなく `rehype-format` を利用しています。そのため長い行が自動改行されることなく維持されます。
議論の必要な点として #48 へコメントしたとおり、この PR の対応で HTML の `DOCTYPE` が README だと大文字で VFM の返すもの (`rehype-document` が付与) は小文字になっていることに気づきました。そのため PR では README に掲載した HTML を実際の出力にあわせて小文字にしてあります。
=> #48 Generated HTML should be human readable

docs/vfm.md, src/plugins/figure.ts, tests/remark2rehype/figure.test.ts
#47 対応です。
- Markdown において画像が単独行として記述された場合のみ、`<figure>` タグへ包みます
- `<img>` が兄弟要素を持たない `<p>` の子であることを条件とします
- 既存の「キャプションが設定されている」という条件は維持し、新たなものと両方を満たしている必要があります
- 画像に属性が指定されていた場合...
- `id` なら `<figure>` へ移動
- その他は [`<img>` 固有の属性](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) 以外を `<figure>` へコピーします
- `<figure>` 処理は `<pre>` も対象としているのですが、こちらは既存実装のままです
- #47 で指摘された `<img>` のみを対象としています
=> #47 Fixed the function to wrap img in figure tag

package.json, tests/attr.test.ts, tests/index.test.ts
And added `test: debug` to package.json to run a single test file. Change the `xxx.test.ts` part to the one you want to test.
=> chor: Added test for attribute syntax

src/plugins/figure.ts, tests/index.test.ts
#77 修正。
Markdown のコード ブロック変換と異なり `<pre>` の解析では `if` で判定している HAST の `properties.title` が存在しない。直後の処理では Optional Chaining で参照しているため、これを `if` 判定にすることで `undefined` 参照によるクラッシュを回避した。
`if` で参照が判定されるため直後の Optional Chaining は不要となる。
=> fix: fixed a crash when specifying the HTML pre tag

src/plugins/figure.ts, tests/remark2rehype/figure.test.ts
#75 対応。
`<img>` に `alt` が設定されていると `<figcaption>` を生成してそのテキストに設定されます。この挙動により Screen Reader が両方を重複して読み上げる副作用があるため、これを防ぐために `<figcaption>` へ属性として `aria-hidden="true"` を設定します。
テスト側の HTML をレビューしてください。提案されたとおりと思われますが、過不足あれば指摘をお願いします。
=> feat: set `aria-hidden: true` to `<figcaption>` so that screen readers don't even read `<img>`'s `alt` and `<figcaption>`

docs/vfm.md, tests/block/metadata.test.ts
2021/4/10 のユーザー会イベントで Frontmetter の `class` に複数の指定は可能か？という質問があったので実証テストを追加。定義された文字列をそのまま設定するだけなので通常の `class` 属性に指定する記法で OK。
=> chor: add test to define multiple classes in frontmetter

tests/html-formatter.test.ts, tests/html-lang.test.ts, tests/metadata.test.ts
私が書いたテストで Jest の `expect` ではなく Node.js の `assert` を使っているものがあったので前者へ統一。Jest 自体は `assert` 互換である。
テスト関数が Jest 標準の `test` ではなく mocha 風な `it` (これもサポートされてる) なのでアサーションも可用性の観点から `assert` にしようと考えたが、部分的にしかそうしていなくて不統一なのと `expect` のわかりやすさもあってこちらへ統一するほうがよいと判断した。
=> chor: unified test stlyles

docs/vfm.md, package.json, src/cli.ts, src/index.ts, src/plugins/math.ts, src/plugins/metadata.ts, src/revive-parse.ts, src/revive-rehype.ts, tests/defs.test.ts, tests/index.test.ts, tests/math.test.ts, tests/metadata.test.ts, tests/utils.ts, types/remark.d.ts, yarn.lock
#37 の議論を踏まえて MathJax 形式の数式構文を実装しました。
@MurakamiShinyu @yamasy1549 
ドキュメント `docs/vfm.md` とテスト `tests/math.test.ts` のレビューをお願いします。
補足として当初は unified のみに依存する独自処理を実装していたのですが、remark を利用するとこれが拡張する tokenizer/method として登録しないと Markdown 構文間の排他がおこなわれないため、VFM 1.0 時点では仕方なく remark プラグインとすることにしました。
VFM 2.0 で remark 13 未満のインターフェースを判定して分岐しているため 13 以降では独自処理に切り替わるはずです。ただし remark 13 でも構文の排他は remark (micromark) として実装しないと機能しないと予想しています。
=> feat: implemented math syntax with MathJax

docs/vfm.md, src/plugins/section.ts, tests/attr.test.ts, tests/index.test.ts, tests/math.test.ts, tests/metadata.test.ts, tests/section.test.ts
#8 で要望されていた機能のうち、
> - Pandoc では section 要素に class 属性 "level1" 〜 "level6" が出力される
>   - これがあると CSS でレベルごとの section のスタイルを指定しやすいので、vfm にもほしい
へ対応してみました。懸念点として `remark-attr` の処理が走ると `id` と `class` の順番が入れ替わる謎の挙動があります。ただしこのプラグイン処理には関与できないのと HTML/CSS 的に属性の定義順へ強く依存するものはないと思われますので実用十分と判断しました。
これを先に実装したのは想定よりも影響範囲が少なくて済みそうであったためです。他の要望については別途、対応を検討します。
ドキュメント `docs/vfm.md` とテスト `test/section.test.ts` についてレビューをお願いします。
=> feat: Added section leveling

docs/vfm.md, src/plugins/section.ts, tests/section.test.ts
#8 のうち以下へ対応しました。
> 2. Pandoc では属性の指定がある見出し（例 `# Heading1 {#id1 .class1 key1=value1}`）で id は section 要素に、それ以外の属性は section 要素と h1-h6 要素の両方に出力される
>     - 現状の vfm ではどの属性も section 要素だけに出力される。Pandoc 同様に h1-h6 要素にも出力されるほうがよいだろう
レビューをお願いします。
=> feat: Copy the section attributes from the heading, however the `id` will be moved

docs/vfm.md, src/plugins/section.ts, tests/section.test.ts
#8 のうち以下に対応。
> 3. Pandoc では blockquote 内の見出し（例 `> # Heading`）では section は作られない
>     - blockquote の内容は本文とは違うものなので、sectionによる構造化の対象にはしないということだろう
レビューお願いします。セクション系の対応が累積しているので `docs/vfm.md` へも属性の扱いなどをまとめて列挙しておきました。
=> feat: Disable section with blockquote heading

README.md, docs/vfm.md, package.json, src/cli.ts, src/index.ts, src/plugins/math.ts, tests/math.test.ts, types/remark.d.ts, yarn.lock
#93 対応。
- `VFM` 関数の `math` オプション既定値を `false` から `true` に変更
- CLI オプション `--math` を `--disable-math` に変更して指定時に無効化
- `math: true` でも実際に数式が処理されなければ `<script>` と `<body>` 属性出力はしないように変更
`docs/vfm.md` と `tests/math.ts` についてレビューをお願いします。
=> feat: Math syntax enabled default

package.json, src/index.ts, src/plugins/document.ts, types/remark.d.ts, yarn.lock
#76 で HTML 周りの大きな設計変更をすることに備え `rehype-document` の実装を独自実装として移植。元は MIT ライセンスなのでその旨、ファイルに TSDoc 形式で注釈した。
=> feat: Implemented document processing as VFM in case of major metadeta design changes

docs/vfm.md
Raw HTML のサンプル HTML で見出しの `<section>` が抜けていたので修正。
=> chore: Fix a document of Raw HTML

docs/vfm.md, src/plugins/document.ts, src/plugins/metadata.ts, tests/metadata.test.ts
#111 修正。
レビューをお願いします。https://github.com/vivliostyle/vfm/issues/111#issuecomment-871301117 のとおり key のみ指定を空文字として扱い、またこれまで空文字で書き込みをスキップしていた `id` や `title` なども属性値や要素の値を空文字として出力するようにしました。
=> fix: Fixed to be empty string instead of null when only key is specified in Frontmatter YAML

docs/vfm.md, src/index.ts, src/plugins/metadata.ts, tests/metadata.test.ts
#98 対応。VFM オプションのうち Frontmatter で被るものとコールバック関数を持つ `replace` を除いて残った以下を `vfm` に追加。
- `partial`
- `hardLineBreaks`
- `disableFormatHtml`
これらは既存の `math` と同じく CLI、`stringify`、`VFM` オプションに優先する。
=> feat: Added VFM settings to Frontmatter

docs/vfm.md, src/plugins/ruby.ts, tests/ruby.test.ts
#32 対応。
@spring-raining 
レビューをお願いします。
`tests/ruby.test.ts` の "Enables escape in ruby body" が本件と対応するものとなります。想定通りか確認してください。
なおテストについて MDAST の検証をやめて HTML のみに変更していますが、これは将来の remark 更新で micromark 対応していないものの処理結果が反映されないことを見越しての対応です。他のテストも私が引き継いでからの新規追加分はそのようにしています。
=> fix: Fixed an issue where ruby couldn't escape pipe with a backslash

docs/vfm.md, src/plugins/document.ts, tests/metadata.test.ts
#119 対応。
提案どおり Frontmatter におけるルートの `class` は `html` と `body` のそれらを上書きするのではなく、スペース区切りで結合されるように実装しました。
この変更にともない仕様書にも解説を追加しています。また仕様書の改訂で目次のリンク間違いも修正しました。
`metadata.test.ts` 末尾に追加した本件のテスト コードと `vfm.md` の新規項目 "Merge class properties" についてレビューをお願いします。
=> feat: Merge the frontmatter's class properties

package.json
正式リリースのための準備。
release-it を dry-run モードで実行するためのスクリプトを追加。Git のコミット候補が残っているとエラーになるので注意。
=> chore: Added script to dry-run release-it

docs/vfm.md
Since VFM v1.0 was released, the basic specifications were fixed. Therefore, the notation "Working Draft" is no longer necessary.
refs #122
=> docs: Deleted "Working Draft" from VFM reference

package.json
Fixed to run as npm-scripts so that it can be published even in an environment without yarn.
=> chore: Delete yarn deps

README.md, src/index.ts, tests/index.test.ts
refs: #130
`stringify` にメタデータ指定可能とした。`VFM` 関数と異なり既定値は Frontmatter を読み込んだものとする。以下の用途を想定。
- Markdown に Frontmatter を定義せずメタデータを指定可能
- Markdown の Frontmatter を `readMetadata` で読み込み加工したものを指定
- Web サイト用 HTML でサイト全体とページ単位 (Markdown) のタイトルを合成するなど
- `Page | Site` のような感じで
=> feat: Supports metadata specification for stringify

docs/ja/vfm.md
The escaping of brackets in the headline is unnecessary, so I removed it.
TOC was generated by npm doctoc.
refs #139
=> fix: Fixed TOC link in Japanese version

README.md, src/plugins/metadata.ts, tests/metadata.test.ts
refs #141
vivliostyle-sitegen など VFM を利用するサードパーティー製ツール用で独自の Frontmatter を定義するため、`readMetadata` に引数 `excludes` を追加。この配列に指定された Frontmatter の YAML キーは `meta` として処理せず `exclude` プロパティー内にキーとデータ型を維持して格納される。
=> feat: Add `excludes` argument to `readMetadata`

README.md, src/plugins/metadata.ts, tests/metadata.test.ts
refs: #143
村上さんと相談した結果、`customKeys` と `custom` がよさそうなので修正しました。あわせて README の API 解説も変更しています。レビューをお願いします。
=> fix: Rename `readMetadata` argument and `Metadata` property `excludes` to be more understandable

src/cli.ts
There is no need to refer to the `message` property of Error because `console.error` will automatically try to stringify it.
=> fix: Type error of object property

docs/index.html
And HTML formatted by prettier.
VFM 仕様ページのサイドバーでテーマ ガイドラインがリンク切れになってた原因を調べたところ、Themes で以下のリンク変更があったことに気づいたのでこちらにも反映。
- [docs: change DESIGN.md link to docs link · vivliostyle/themes@ae331bc](https://github.com/vivliostyle/themes/commit/ae331bcc2f4b02941f1fadec4f14e35286d8864c)
=> docs: Change DESIGN.md link to docs link

src/plugins/metadata.ts
This PR will fix #134 issue
**Before**
```bash
$ echo "# Foo {.foo}" | vfm
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Foo {.foo}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<section class="level1 foo" id="foo">
<h1 class="foo">Foo</h1>
</section>
</body>
</html>
```
**After**
```bash
$ echo "# Foo {.foo}" | vfm
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Foo</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<section class="level1 foo" id="foo">
<h1 class="foo">Foo</h1>
</section>
</body>
</html>
```
---
This issue also affecting generated toc in **vivliostyle-cli**.
**Generated toc before**
**Generated toc after**
=> fix: remove heading attributes notation on page title

tests/metadata.test.ts
refs #148
↑の PR は私の手元でも動作を確認済みだが、ユニット テストを追加して動作を明示しておく。
=> chore: Added test to exclude attribute syntax in title heading

docs/ja/vfm.md, docs/vfm.md, src/plugins/figure.ts, tests/figure.test.ts
- resolves #151
画像に指定された属性をfigure要素にコピー（idは移動）しないようにしました。
=> feat: disable image attributes copy to figure element

docs/index.html
日本語ドキュメントのサイドバーが壊れてたのに気がつき修正しました。
スクリーンショット
修正前
サイドバーの「Spec→VFM」をクリックしてもVFM仕様の日本語の目次が展開されることはなく、英語のVFM仕様のドキュメントに移動してしまいます。
また、右上の「ホーム」のリンクのところに「Vivliostyle」と「GitHub」のリンクもあるべきなのですが、それらがありません。
修正後
=> docs: 日本語ドキュメントのサイドバーが壊れていたのを修正

src/index.ts, tests/metadata.test.ts
Added this attribute because CSS was not applied correctly without it on e-reader devices (Checked on Kindle paperwhite 11th).
こちらのCLIと共通の修正です。
https://github.com/vivliostyle/vivliostyle-cli/pull/448
=> Added Type attribute to Link of CSS

src/plugins/section.ts, tests/section.test.ts
=> fix: HTML block with markdown heading causes wrong HTML sectioning

package.json
Vivliostyle CLI の下限 Node.js バージョンが 16 なので、VFM も踏襲します。
=> chore: [Breaking Change] Update support version of Node.js

src/plugins/section.ts
- fix #183
この不具合は、 #174 で追加したHTMLブロックでの終了タグがあったら対応する開始タグが同じセクションのレベルになかったらセクションを閉じるようにするという処理に問題があり発生していました。
複数の終了タグからなるHTMLブロック（例 `</td></tr></table>`）があったとき、今回の修正前は、その最初の終了タグのタグ名（この例では `td`）の開始タグではじまるHTMLブロックを見つけるようにしていました。これでは対応する開始タグが見つからない（`<table><tr><td>` というHTMLブロックではマッチしない）ということがあるため、この不具合が起きていました。
この修正後では、HTMLブロック内に複数のタグがあっても問題ないように、HTMLブロック内の最後の終了タグと対応する開始タグを見つけるようにしました。
また、対応する開始タグが同じセクションのレベルになかった場合、それより前に見つかるかどうかをチェックして、もし見つからなかった場合は、セクションを閉じることはしないようにしました。
=> fix: HTML block causes wrong sectioning (vfm 2.2.0)

docs/ja/vfm.md, docs/vfm.md
VFM 構文ドキュメントにおいて Sectionization は最新仕様になっているが、Raw HTML のサンプル HTML は古いままだったので修正。
=> fix: Raw HTML のサンプル HTML を最新の Section 仕様に修正

docs/ja/vfm.md, docs/vfm.md
セクション分けの例を修正しました。
- セクションを終了させる `##` だけの行の例を入れた
- セクション分けをしない見出しの例を入れた
- CSSセレクタの `body > section > h1:first-child` はあまり有用でないと思う（たぶんこの例が書かれたのはVFM v1で見出しの属性がsectionに付く仕様だったので見出しだけの選択がしにくかったことが関係する）ので削除
- sectionの選択に`aria-labelledby`属性を使った例を追加
- sectionの選択に`:has()`を使った例を追加
=> docs: improve sectionization example

docs/ja/vfm.md, docs/vfm.md
=> docs: deprecate aria-labelledby output

README.md, docs/ja/vfm.md, jest.config.js, package-lock.json, package.json, tests/attr.test.ts, tests/code.test.ts, tests/defs.test.ts, tests/figure.test.ts, tests/footnotes.test.ts, tests/html-formatter.test.ts, tests/html-lang.test.ts, tests/index.test.ts, tests/line-breaks.test.ts, tests/markdown-inside-html.test.ts, tests/math.test.ts, tests/metadata.test.ts, tests/ruby.test.ts, tests/section.test.ts, tests/utils.ts
ESM 対応を容易にするため、テストを Jest から Vitest へ移行しました。
- Vitest は Jest 互換の API を持ち、標準で TypeScript + ESM 対応しています
- Vitest 移行にともない、テスト コードを以下のように変更しています
- `it` を `test` に変更
- Vitest 的にはどちらも利用可能
- Vitest サンプルが `test` なのと、こちらの方が第三者にテスト関数であることがわかりやすい
- `test` や `expect` を明示的 import に変更
- Vitest には Jest のように参照を暗黙解決するモードもあります
- ただし Vitest 標準は明示、かつこのほうがレビュー時にファイル単体で見てもわかりやすい
- hursky、lint-stage 関連を削除
- git commit 時の Lint 強制はメリットだが、かつてライセンス変更があったり管理対象 npm と設定が多いなどメンテナンスに難あり
- VFM 開発者が現状、私ぐらいしかいないので Lint 強制メリットもあまり享受できてない
- 以上と Vitest 周りで設定変更が必要なようなので削除 (廃止) しました
- プロジェクト立ち上げ当初、開発体験を向上させるために様々なパッケージを導入していましたが、それらにも継続的な運用 (管理) コストがかかるのでいったん必要最小にしてゆきます
- 本 PR で Vitest を no-config 運用 (標準設定) にしたのも、この一環となります
=> feat: ESM 対応を容易にするため、テストを Jest から Vitest へ移行
